#ifndef __CDMACDEV_H
#define __CDMACDEV_H

#define CDMACDEV_IOC_SET_DEV_ADDR 101       // 0x65
#define CDMACDEV_IOC_GET_DEV_ADDR 102       // 0x66
#define CDMACDEV_IOC_SET_DATA_SIZE 103      // 0x67
#define CDMACDEV_IOC_GET_DATA_SIZE 104      // 0x68
#define CDMACDEV_IOC_SET_CPU_ADDR 105       // 0x69
#define CDMACDEV_IOC_GET_CPU_ADDR 106       // 0x6A
#define CDMACDEV_IOC_FREE_DEVBUF 107        // 0x6B
#define CDMACDEV_IOC_FREE_CPUBUF 108        // 0x6C
#define CDMACDEV_IOC_SET_DIRECTION 109      // 0x6D
#define CDMACDEV_IOC_GET_DIRECTION 110      // 0x6E
#define CDMACDEV_IOC_DO_TRANSFER 111        // 0x6F
#define CDMACDEV_IOC_FILL_BUFFER 112        // 0x70
#define CDMACDEV_IOC_COMPARE_BUFFER 113     // 0x71

#define CDMACDEV_DIR_DEV_TO_MEM 0
#define CDMACDEV_DIR_MEM_TO_DEV 1

#endif